version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  backend:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static/
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network


volumes:
  db_data:
  static_volume:
  redis_data:
